services:
  kube-monitor-probe:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kube-monitor-probe
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=kube-monitor-probe-kit
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    volumes:
      - applogs:/app/logs
    depends_on:
      - otel-collector
    networks:
      - monitoring-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otelcol/otel-collector-config.yaml:ro
      - applogs:/app/logs:ro
    depends_on:
      - loki
      - jaeger
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring-network

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    networks:
      - monitoring-network

    tempo:
      image: grafana/tempo:2.5.0
      container_name: tempo
      command: [ "-config.file=/etc/tempo/tempo.yaml" ]
      volumes:
        - ./tempo:/etc/tempo
      ports:
        - "${TEMPO_HTTP_PORT}:3200"
        - "${TEMPO_OTLP_GRPC_PORT}:4317"
        - "${TEMPO_OTLP_HTTP_PORT}:4318"
      networks:
        - monitoring-network

  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - jaeger
      - prometheus
      - loki
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  applogs: