global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kube-monitor-probe'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['kube-monitor-probe:8080']
        labels:
          app: kube-monitor-probe-kit

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          app: otel-collector